// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx3NL37923rF2FFn9WGbgkAu21Rjy7CIk',
    appId: '1:89254989384:web:e21523b0fefdf2b426d27d',
    messagingSenderId: '89254989384',
    projectId: 'chat-2gether',
    authDomain: 'chat-2gether.firebaseapp.com',
    storageBucket: 'chat-2gether.appspot.com',
    measurementId: 'G-3V5SQ8K7CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP-VEzgEi8FHteUPMG_Ggiq1nY0OWK-Dc',
    appId: '1:89254989384:android:af55d684c9761ae726d27d',
    messagingSenderId: '89254989384',
    projectId: 'chat-2gether',
    storageBucket: 'chat-2gether.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAfSnJqkrULhmgiEGR-6xFN32S6W7VTII',
    appId: '1:89254989384:ios:ba34c2a5260c0b2926d27d',
    messagingSenderId: '89254989384',
    projectId: 'chat-2gether',
    storageBucket: 'chat-2gether.appspot.com',
    iosClientId: '89254989384-prnpbbe0il8pcuagu239qj3cvoqjc7tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat2gether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAfSnJqkrULhmgiEGR-6xFN32S6W7VTII',
    appId: '1:89254989384:ios:ba34c2a5260c0b2926d27d',
    messagingSenderId: '89254989384',
    projectId: 'chat-2gether',
    storageBucket: 'chat-2gether.appspot.com',
    iosClientId: '89254989384-prnpbbe0il8pcuagu239qj3cvoqjc7tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat2gether',
  );
}
